"""Phase 2 centralized error codes."""

# Source artifact policy
DERIVED_SOURCE_NOT_ALLOWED = "DERIVED_SOURCE_NOT_ALLOWED"
INVALID_SOURCE_LAYER = "INVALID_SOURCE_LAYER"
SOURCE_ARTIFACT_LAYER_MISMATCH = "SOURCE_ARTIFACT_LAYER_MISMATCH"
SOURCE_ARTIFACT_DENYLISTED = "SOURCE_ARTIFACT_DENYLISTED"
SOURCE_ARTIFACT_NOT_CANONICALIZABLE = "SOURCE_ARTIFACT_NOT_CANONICALIZABLE"
SOURCE_ARTIFACT_NOT_HASHED = "SOURCE_ARTIFACT_NOT_HASHED"
SOURCE_ARTIFACT_NOT_AUTHORITATIVE = "SOURCE_ARTIFACT_NOT_AUTHORITATIVE"

# Derived artifact policy
DERIVED_ARTIFACT_NOT_ALLOWED = "DERIVED_ARTIFACT_NOT_ALLOWED"
DERIVED_PATH_OUTSIDE_WORKSPACE = "DERIVED_PATH_OUTSIDE_WORKSPACE"
SYMLINK_DERIVED_PATH_REJECTED = "SYMLINK_DERIVED_PATH_REJECTED"
PATH_ESCAPE_REJECTED = "PATH_ESCAPE_REJECTED"

# Hash
HASH_ENCODING_INVALID = "HASH_ENCODING_INVALID"
JSON_FLOAT_NOT_ALLOWED = "JSON_FLOAT_NOT_ALLOWED"

# Summary
SUMMARY_NOT_DERIVED = "SUMMARY_NOT_DERIVED"
SUMMARY_SOURCE_NOT_ALLOWED = "SUMMARY_SOURCE_NOT_ALLOWED"
SUMMARY_SOURCE_LAYER_INVALID = "SUMMARY_SOURCE_LAYER_INVALID"
SUMMARY_STALE = "SUMMARY_STALE"
SUMMARY_MISSING = "SUMMARY_MISSING"
SUMMARY_MULTIPLE_CANDIDATES = "SUMMARY_MULTIPLE_CANDIDATES"
SUMMARY_SOURCE_PATH_MISMATCH = "SUMMARY_SOURCE_PATH_MISMATCH"

# Apply
APPLY_DERIVED_SOURCE_REJECTED = "APPLY_DERIVED_SOURCE_REJECTED"

# Retrieval
RETRIEVAL_TRACE_NESTED_SCHEMA_UNSUPPORTED = "RETRIEVAL_TRACE_NESTED_SCHEMA_UNSUPPORTED"
