"""Verify test baseline from JUnit XML and generate baseline documentation."""

import argparse
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def parse_junit_xml(xml_path):
    """Parse JUnit XML, return dict with passed/failed/errors/skipped/skipped_tests list.

    Handles both <testsuites> and <testsuite> root elements.
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()

    # Normalize: find all <testsuite> elements regardless of root tag
    if root.tag == "testsuites":
        suites = root.findall("testsuite")
    elif root.tag == "testsuite":
        suites = [root]
    else:
        raise ValueError(f"Unexpected root element: {root.tag}")

    total = 0
    failures = 0
    errors = 0
    skipped = 0
    skipped_tests = []

    for suite in suites:
        total += int(suite.get("tests", 0))
        failures += int(suite.get("failures", 0))
        errors += int(suite.get("errors", 0))
        skipped += int(suite.get("skipped", 0))

        for tc in suite.findall("testcase"):
            skip_elem = tc.find("skipped")
            if skip_elem is not None:
                classname = tc.get("classname", "")
                name = tc.get("name", "")
                message = skip_elem.get("message", "")
                skipped_tests.append({
                    "classname": classname,
                    "name": name,
                    "message": message,
                })

    passed = total - failures - errors - skipped

    return {
        "total": total,
        "passed": passed,
        "failed": failures,
        "errors": errors,
        "skipped": skipped,
        "skipped_tests": skipped_tests,
    }


def generate_baseline_md(results, base_commit, python_version):
    """Generate markdown with table of results + skipped test list.

    Includes DO NOT EDIT header.
    """
    lines = [
        "<!-- DO NOT EDIT — generated by tools/verify_test_baseline.py -->",
        "",
        "# Phase 2 Test Baseline",
        "",
        f"**Base Commit:** {base_commit}",
        f"**Python:** {python_version}",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|--------|-------|",
        f"| Total | {results['total']} |",
        f"| Passed | {results['passed']} |",
        f"| Failed | {results['failed']} |",
        f"| Errors | {results['errors']} |",
        f"| Skipped | {results['skipped']} |",
        "",
    ]

    if results["skipped_tests"]:
        lines.append("## Skipped Tests")
        lines.append("")
        for t in results["skipped_tests"]:
            short_class = t["classname"].rsplit(".", 1)[-1]
            lines.append(f"- `{short_class}::{t['name']}` — {t['message']}")
        lines.append("")

    return "\n".join(lines)


def project_root():
    return Path(__file__).resolve().parent.parent


def resolve_base_commit(commit, root):
    if commit:
        return commit

    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=root,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", "") or str(exc)
        print(f"ERROR: unable to resolve git HEAD for baseline: {detail}", file=sys.stderr)
        sys.exit(2)

    resolved = result.stdout.strip()
    if not resolved:
        print("ERROR: git HEAD resolved to an empty commit", file=sys.stderr)
        sys.exit(2)
    return resolved


def check_consistency(results, project_root):
    """Regex check README.md and docs/phase2_protocol_freeze_verification.md
    for test count patterns. Return list of error strings.
    """
    errors = []
    expected_passed = str(results["passed"])
    expected_total = str(results["total"])

    files_to_check = [
        Path(project_root) / "README.md",
        Path(project_root) / "docs" / "phase2_protocol_freeze_verification.md",
    ]

    # Pattern: look for hardcoded numeric test counts like "312+" or "311 passed"
    # but allow references to the generated baseline file
    count_pattern = re.compile(r"\b\d{2,}\+?\s*(passed|tests?)\b", re.IGNORECASE)

    for fpath in files_to_check:
        if not fpath.exists():
            continue
        text = fpath.read_text(encoding="utf-8")
        for m in count_pattern.finditer(text):
            errors.append(
                f"{fpath.name}: found hardcoded test count '{m.group()}' at "
                f"offset {m.start()}. Reference the generated baseline instead."
            )

    return errors


def main():
    parser = argparse.ArgumentParser(
        description="Verify test baseline from JUnit XML"
    )
    parser.add_argument(
        "--junit", required=True, help="Path to JUnit XML report"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check docs for hardcoded test counts",
    )
    parser.add_argument(
        "--output",
        default="docs/phase2_test_baseline.generated.md",
        help="Output path for generated baseline (default: docs/phase2_test_baseline.generated.md)",
    )
    parser.add_argument(
        "--commit",
        default=None,
        help="Base commit hash to record in baseline",
    )
    parser.add_argument(
        "--python",
        default=f"{sys.version_info.major}.{sys.version_info.minor}",
        help="Python version to record in baseline",
    )
    args = parser.parse_args()

    results = parse_junit_xml(args.junit)
    base_commit = resolve_base_commit(args.commit, project_root())

    # Always generate baseline
    md = generate_baseline_md(results, base_commit, args.python)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    print(f"Baseline written to {out_path}")
    print(f"  Total: {results['total']}, Passed: {results['passed']}, "
          f"Failed: {results['failed']}, Errors: {results['errors']}, "
          f"Skipped: {results['skipped']}")

    # Optionally check consistency
    if args.check:
        root = project_root()
        errs = check_consistency(results, root)
        if errs:
            print(f"\nConsistency check found {len(errs)} issue(s):")
            for e in errs:
                print(f"  - {e}")
            sys.exit(1)
        else:
            print("\nConsistency check passed — no hardcoded test counts found.")

    # Exit non-zero if there are failures or errors
    if results["failed"] > 0 or results["errors"] > 0:
        print(f"\nWARNING: {results['failed']} failed, {results['errors']} errors")
        sys.exit(2)


if __name__ == "__main__":
    main()
